### ISSUE TITLE
GPU version hangs infedefinitely

### ISSUE THREAD

**Issue by ara1618** [TurkuNLP/Turku-neural-parser-pipeline#31]
The CPU version runs ok, but when we attempt to run streaming mode / server mode on the GPU, the docker hangs indefinitely:
> Initial # of tokens in buckets: 875724
> Final # of tokens in buckets: 818891
> Initial # of tokens in buckets: 123
> Final # of tokens in buckets: 123
> Bucket parseset-0 is 4 x 7 x 9
> Bucket parseset-1 is 4 x 10 x 9
> Bucket parseset-2 is 3 x 12 x 9
> Bucket parseset-3 is 3 x 14 x 9
> Bucket parseset-4 is 3 x 16 x 9
> Initial # of tokens in buckets: 875724
> Final # of tokens in buckets: 818891
> Initial # of tokens in buckets: 128
> Final # of tokens in buckets: 128
> Bucket parseset-0 is 4 x 6 x 9
> Bucket parseset-1 is 4 x 9 x 9
> Bucket parseset-2 is 4 x 12 x 9
> Bucket parseset-3 is 3 x 14 x 9
> Bucket parseset-4 is 3 x 16 x 9

We are also getting the following dissonant error message:
> RuntimeError: CuDNN error: CUDNN_STATUS_SUCCESS

Tested both on Cuda versions 9.2 and 10.2., on Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-96-generic x86_64). Any ideas why this could be?

**Comment by ara1618** [comment]
Found out that the container has an inbuilt Cuda version 9.0 - perhaps this is not compatible with our GPU (GeForce RTX 2080 Ti)?

**Comment by festkonfekt** [comment]
Experiencing the same problem with GeForce RTX 2080 and Windows 10, tested with CUDA version 9.0 - no use. CPU version works fine.

**Comment by SanteriHei** [comment]
I'm running GeForce RTX 2080 Super on Windows 10 and I was able to fix this problem by upgrading my CUDA version to 9.2. Seems to be a problem related to the whole RTX 2080 line according to this thread: [https://discuss.pytorch.org/t/runtimeerror-cudnn-error-cudnn-status-success/28045](https://discuss.pytorch.org/t/runtimeerror-cudnn-error-cudnn-status-success/28045l). I did the upgrade using conda and by following these instructions: [https://pytorch.org/get-started/previous-versions/](https://pytorch.org/get-started/previous-versions/)  (Commands for Versions < 1.0.0).
